import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
// import Footer from "@/components/layouts/Footer";
import { cn } from "@/lib/utils";

const lato = Lato({ subsets: ["latin"], variable: "--font-sans", weight: ["400", "700"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Aldi Property | Bantu Kamu Menemukan Hunian Terbaikmu",
  description:
    "Miliki townhouse eksklusif modern tropis di Cilandak, Jakarta Selatan. Lokasi strategis, fasilitas smart home, dan akses premium. Mulai Rp 4,7 Miliar.",
  keywords: [
    "Pranara Cilandak",
    "Pranara Land",
    "townhouse jakarta selatan",
    "rumah mewah cilandak",
    "rumah 3 lantai jakarta selatan",
    "properti premium cilandak",
    "cluster eksklusif jakarta selatan",
  ],
  authors: [{ name: "Pranara Land" }],
  openGraph: {
    title: "Pranara Cilandak | Hunian Mewah 3 Lantai di Jakarta Selatan",
    description:
      "Miliki townhouse eksklusif modern tropis di Cilandak, Jakarta Selatan. Lokasi strategis, fasilitas smart home, dan akses premium.",
    url: "https://domainkamu.id", // Ganti dengan domain yang baru kamu beli dari Niagahoster
    siteName: "Pranara Cilandak",
    images: [
      {
        url: "https://cdn.pixabay.com/photo/2017/07/08/02/16/house-2483336_1280.jpg", // Gambar default saat link dibagikan
        width: 1200,
        height: 630,
        alt: "Pranara Cilandak Premium Townhouse",
      },
    ],
    locale: "id_ID",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Pranara Cilandak | Hunian Mewah 3 Lantai di Jakarta Selatan",
    description: "Miliki townhouse eksklusif modern tropis di Cilandak, Jakarta Selatan. Mulai Rp 4,7 Miliar.",
    images: ["https://cdn.pixabay.com/photo/2017/07/08/02/16/house-2483336_1280.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-sans", "scroll-smooth", lato.variable)}>
      <body className="min-h-full flex flex-col">
        <Header />
        <div className="grow">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
